
# Set-up Prometheus to scrape Cadvisor metrics every 5 seconds. 

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
      - targets: 
      # Targeting the cadvisor host
        - 'host.docker.internal:9101'
      